version: "3.7"

services:
  frontend:
    build: ./frontend
    ports:
      - "80:5000"
    environment:
      PORT_FRONT: "5000"
      URL_BACK: "localhost"
      PORT_BACK: "5001"

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      URL_FRONT: "localhost"
      PORT_FRONT: "5000"
      PORT_BACK: "5001"
      URL_DB: "localhost"
      PORT_DB: "3306"

  db:
    build: ./database
#    ports:
#      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "passwd"
      MYSQL_DATABASE: "lab_db"
    volumes:
      - ./dump_db.sql:/docker-entrypoint-initdb.d/dump.sql
